### ISSUE TITLE
I got some errors

### ISSUE THREAD

**Issue by xstoop** [mgjohansen/hucore#1]
» hugo server -t hucore -D
Started building sites ...
ERROR: 2017/03/14 23:44:12 template.go:132: template: theme/partials/header.html:5:18: executing "theme/partials/header.html" at <delimit .Site.Params...>: error calling delimit: can't iterate over <nil> in theme/partials/header.html
ERROR: 2017/03/14 23:44:12 template.go:132: template: theme/partials/header.html:5:18: executing "theme/partials/header.html" at <delimit .Site.Params...>: error calling delimit: can't iterate over <nil> in theme/partials/header.html
ERROR: 2017/03/14 23:44:12 template.go:132: template: theme/partials/header.html:5:18: executing "theme/partials/header.html" at <delimit .Site.Params...>: error calling delimit: can't iterate over <nil> in theme/partials/header.html
ERROR: 2017/03/14 23:44:12 template.go:132: template: theme/partials/header.html:5:18: executing "theme/partials/header.html" at <delimit .Site.Params...>: error calling delimit: can't iterate over <nil> in theme/partials/header.html
ERROR: 2017/03/14 23:44:12 template.go:132: template: theme/partials/header.html:5:18: executing "theme/partials/header.html" at <delimit .Site.Params...>: error calling delimit: can't iterate over <nil> in theme/partials/header.html

this is my hugo env

» hugo env
Hugo Static Site Generator v0.17 BuildDate: 2016-10-07T22:42:05+08:00
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.7.1"

I copied your example config.toml to my project.
Even I got above ERROR messages, I still could see my content in web page in chrome, but it haven't any css style be included.
what I did some wrong?

**Comment by aac** [comment]
I'm having this error too, while using Hucore as the theme and following the automated deployment process here: http://gohugo.io/tutorials/automated-deployments/#adding-a-deploy-pipeline

**Comment by ghost** [comment]
Same here:

**# hugo server -w -v**
INFO 2017/05/16 11:26:18 Using config file: 
INFO 2017/05/16 11:26:18 using a UnionFS for static directory comprised of:
INFO 2017/05/16 11:26:18 Base: /home/myuser/projetos/classified/themes/hucore/static
INFO 2017/05/16 11:26:18 Overlay: /home/myuser/projetos/classified/static/
INFO 2017/05/16 11:26:18 syncing static files to /
WARN 2017/05/16 11:26:18 No translation bundle found for default language "en"
WARN 2017/05/16 11:26:18 Translation func for language en not found, use default.
WARN 2017/05/16 11:26:18 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
Started building sites ...
INFO 2017/05/16 11:26:18 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
ERROR 2017/05/16 11:26:18 Error while rendering "page": template: theme/_default/single.html:2:3: executing "theme/_default/single.html" at <partial "header" .>: error calling partial: template: theme/partials/header.html:5:18: executing "theme/partials/header.html" at <delimit .Site.Params...>: error calling delimit: can't iterate over <nil>
WARN 2017/05/16 11:26:18 [en] Unable to locate layout for "taxonomyTerm": [taxonomy/tag.terms.html.html taxonomy/tag.terms.html _default/terms.html.html _default/terms.html indexes/indexes.html.html indexes/indexes.html theme/taxonomy/tag.terms.html.html theme/taxonomy/tag.terms.html theme/_default/terms.html.html theme/_default/terms.html theme/indexes/indexes.html.html theme/indexes/indexes.html]
ERROR 2017/05/16 11:26:18 Error while rendering "section": template: theme/_default/list.html:1:3: executing "theme/_default/list.html" at <partial "header" .>: error calling partial: template: theme/partials/header.html:5:18: executing "theme/partials/header.html" at <delimit .Site.Params...>: error calling delimit: can't iterate over <nil>
ERROR 2017/05/16 11:26:18 Error while rendering "home": template: theme/_default/list.html:1:3: executing "theme/_default/list.html" at <partial "header" .>: error calling partial: template: theme/partials/header.html:5:18: executing "theme/partials/header.html" at <delimit .Site.Params...>: error calling delimit: can't iterate over <nil>
WARN 2017/05/16 11:26:18 [en] Unable to locate layout for "taxonomyTerm": [taxonomy/category.terms.html.html taxonomy/category.terms.html _default/terms.html.html _default/terms.html indexes/indexes.html.html indexes/indexes.html theme/taxonomy/category.terms.html.html theme/taxonomy/category.terms.html theme/_default/terms.html.html theme/_default/terms.html theme/indexes/indexes.html.html theme/indexes/indexes.html]
ERROR 2017/05/16 11:26:18 Error while rendering "404": template: theme/404.html:1:3: executing "theme/404.html" at <partial "header" .>: error calling partial: template: theme/partials/header.html:5:18: executing "theme/partials/header.html" at <delimit .Site.Params...>: error calling delimit: can't iterate over <nil>
Built site for language en:
0 draft content
0 future content
0 expired content
1 regular pages created
8 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 10 ms
WARN 2017/05/16 11:26:18 Skip i18nDir: lstat /home/myuser/projetos/classified/i18n: no such file or directory
Watching for changes in /home/myuser/projetos/classified/{data,content,layouts,static,themes}
WARN 2017/05/16 11:26:18 Skip i18nDir: lstat /home/myuser/projetos/classified/i18n: no such file or directory
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)

**# hugo env**
Hugo Static Site Generator v0.20.7 linux/amd64 BuildDate: 2017-05-03T04:39:25-03:00
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.8.1"

**Comment by bengadbois** [comment]
I have found a solution.

This occurs due a case sensitive issue config issue in older version hugo. In config.toml change `[params]` to `[Params]`.

In `layouts/partials/header.html`, `<meta content="{{ .Site.Params.Author }}" name="author">` (and others) is looking for `Params` with a capital "P".

**Comment by lunemec** [comment]
I was having the same errors, and it turns out that you *need* to specify `[params]` or it will not work.

**Comment by ishehata** [comment]
it seems that issue should be closed now.
