### ISSUE TITLE
Could you please add a property to change favicon?

### ISSUE THREAD

**Issue by acche** [mgjohansen/hucore#16]
Is there any way to change favicon for website?

**Comment by mtn** [comment]
Hey @ACChe, I don't actually use this theme but was just passing by and can help :)

The current favicon is ![this](https://raw.githubusercontent.com/mgjohansen/hucore/master/static/wave.ico), right? You can change this pretty easily either by editing the header partial template (`layouts/partials/header.html`) in line 23:

```
<link rel="shortcut icon" href="{{ .Site.BaseURL }}/wave.ico">
```

You can put your favicon in the `static` directory of your theme clone and then change the line to use it. Feel free to ping me if this was unclear.

**Comment by acche** [comment]
OK, DONE.
