### ISSUE TITLE
Strange layout 

### ISSUE THREAD

**Issue by yahmad** [mgjohansen/hucore#2]
Hey, I love the look of the theme but am having some issues with the layout. 😢 

I followed your 'Getting Started' guide, but the layout of the page is not correct. I am seeing this with the Hemingway and Hemingway2 themes as well, but not other themes I have tried.

_It looks like this:_

<img src="https://cloud.githubusercontent.com/assets/2039415/24682241/7d870a68-1990-11e7-8373-7940168ddc7b.png" width="50%">

Any ideas what could be causing the issue? A missing step or some dependency problem?

No errors given. 
Using Hugo **v0.19**.

**Comment by casidiablo** [comment]
This happened to me too. What happened, apparently, is that I had tried another theme before this one, and the browser kept the style.css file cached so when I switched to this theme everything looked just like in your screenshot. Forcing the browser to load the new style.css fixed it (Command + Shift + R in Chrome)

**Comment by yahmad** [comment]
Belated thanks, I moved away to using another static-site solution and it sounds like a hard refresh would have solved this issue.
