### ISSUE TITLE
no such template "theme/_default/list.html"

### ISSUE THREAD

**Issue by eest** [mgjohansen/hucore#22]
I noticed I was not able to update my blog with a recent version of hugo.

This is what I am running:
```
$ hugo version
Hugo Static Site Generator v0.42.1 linux/amd64 BuildDate: 2018-06-13T20:49:30+0200
```
... and this is the error I receive:
```
$ hugo
Building sites … ERROR 2018/07/01 08:20:53 Error while rendering "home" in "": html/template:index.html:1:12: no such template "theme/_default/list.html"
```

How to reproduce:
```
$ hugo new site quickstart
[...]
$ cd quickstart/
$ git init
$ git submodule add https://github.com/mgjohansen/hucore.git themes/Hucore
```

... add a minimal config.toml based on example from https://themes.gohugo.io/hucore/:
```
baseurl = "https://example.com"
languageCode = "en"
title = "Hu | Core"
theme = "Hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/mgjohansen\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"

[params]
description = "Your description here"
keywords = ["keyword 1", "keyword 2", "keyword 3"] 
author = "Morten G. Johansen"
```
... and finally try to build the site:
```
$ hugo
Building sites … ERROR 2018/07/01 08:27:17 Error while rendering "home" in "": html/template:index.html:1:12: no such template "theme/_default/list.html"
```

**Comment by itaditya** [comment]
I'm getting the same error. It's my first time trying hucore. @eest do you know an older version which works

**Comment by itaditya** [comment]
@mgjohansen I really like this theme, and I absolutely want to use it. Can you please take a look. I'd also love to help you out in any way possible

**Comment by eest** [comment]
@itaditya I ended up switching to a similar theme: https://themes.gohugo.io/kiss/

**Comment by itaditya** [comment]
@eest thanks I'll check that out. I was able to fix the issue though. Check my PR.

**Comment by eest** [comment]
@itaditya yeah I noticed you had submitted a PR, well done :). I have not tested it since I won't be migrating back at this point but it should be promising for other people!
